// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/albums/Epic-Myths/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/StickerSet.tsx";
import * as $$1 from "./islands/Timer.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/albums/Epic-Myths/index.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/StickerSet.tsx": $$0,
    "./islands/Timer.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
